server:
  port: 8081

spring:
  application:
    name: BibliotecaOnline

  datasource:
    url: jdbc:h2:file:./data/biblioteca
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console 

  flyway:
    enabled: false
  
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: smtp@mailtrap.io
    password: 0aba6aa3c84efcd0fbdf6191e7ecb06d
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # ✅ SEÇÃO ADICIONADA PARA LIMITES DE UPLOAD (MB)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB